name: advance
channels:
  - defaults
dependencies:
  - aiodns=3.5.0
  - aiohappyeyeballs=2.6.1
  - aiohttp=3.12.15
  - aiosignal=1.4.0
  - alabaster=0.7.16
  - anyio=4.10.0
  - aom=3.6.0
  - applaunchservices=0.3.0
  - appnope=0.1.4
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=25.1.0
  - arrow=1.3.0
  - astroid=3.3.11
  - asttokens=3.0.0
  - async-lru=2.0.4
  - async-timeout=5.0.1
  - asyncssh=2.17.0
  - atomicwrites=1.4.0
  - attrs=24.3.0
  - autopep8=2.0.4
  - babel=2.16.0
  - backports.tarfile=1.2.0
  - bcrypt=4.3.0
  - beautifulsoup4=4.13.5
  - binaryornot=0.4.4
  - black=25.1.0
  - blas=1.0
  - bleach=6.2.0
  - bottleneck=1.4.2
  - brotlicffi=1.0.9.2
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.9.9
  - cairo=1.18.4
  - certifi=2025.10.5
  - cffi=2.0.0
  - chardet=5.2.0
  - charset-normalizer=3.3.2
  - click=8.2.1
  - cloudpickle=3.1.1
  - comm=0.2.1
  - contourpy=1.3.1
  - cookiecutter=2.6.0
  - cryptography=46.0.2
  - cycler=0.11.0
  - cyrus-sasl=2.1.28
  - dav1d=1.2.1
  - debugpy=1.8.16
  - decorator=5.2.1
  - defusedxml=0.7.1
  - deprecated=1.2.18
  - diff-match-patch=20200713
  - dill=0.4.0
  - docstring-to-markdown=0.17
  - docutils=0.21.2
  - exceptiongroup=1.2.0
  - executing=2.2.1
  - expat=2.7.1
  - flake8=7.1.1
  - fontconfig=2.15.0
  - fonttools=4.60.1
  - freetype=2.13.3
  - fribidi=1.0.10
  - frozenlist=1.5.0
  - gettext=0.21.0
  - glib=2.84.2
  - glib-tools=2.84.2
  - graphite2=1.3.14
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - harfbuzz=10.2.0
  - icu=73.1
  - idna=3.7
  - imagesize=1.4.1
  - importlib-metadata=8.5.0
  - inflection=0.5.1
  - intervaltree=3.1.0
  - ipykernel=6.30.1
  - ipython=8.30.0
  - ipywidgets=8.1.5
  - isort=6.1.0
  - jaraco.classes=3.4.0
  - jaraco.context=6.0.0
  - jaraco.functools=4.1.0
  - jedi=0.19.2
  - jellyfish=1.1.3
  - jinja2=3.1.6
  - joblib=1.5.2
  - jpeg=9f
  - json5=0.9.25
  - jsonschema=4.25.0
  - jsonschema-specifications=2023.7.1
  - jupyter=1.1.1
  - jupyter-lsp=2.2.5
  - jupyter_client=8.6.3
  - jupyter_console=6.6.3
  - jupyter_core=5.8.1
  - jupyter_events=0.12.0
  - jupyter_server=2.16.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.0.11
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - jupyterlab_widgets=3.0.15
  - keyring=25.6.0
  - kiwisolver=1.4.8
  - krb5=1.20.1
  - lcms2=2.16
  - lerc=4.0.0
  - libabseil=20250127.0
  - libavif=1.1.1
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcurl=8.15.0
  - libcxx=20.1.8
  - libdeflate=1.22
  - libedit=3.1.20230828
  - libev=4.33
  - libevent=2.1.12
  - libffi=3.4.4
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libglib=2.84.2
  - libiconv=1.16
  - libkrb5=1.21.3
  - libllvm14=14.0.6
  - libnghttp2=1.57.0
  - libopenblas=0.3.30
  - libpng=1.6.39
  - libpq=17.4
  - libprotobuf=5.29.3
  - libsodium=1.0.20
  - libspatialindex=1.9.3
  - libssh2=1.11.1
  - libtiff=4.7.0
  - libuv=1.48.0
  - libwebp-base=1.3.2
  - libxml2=2.13.8
  - libzlib=1.3.1
  - llvm-openmp=20.1.8
  - lmdb=0.9.31
  - lz4-c=1.9.4
  - markdown-it-py=4.0.0
  - markupsafe=3.0.2
  - matplotlib=3.10.6
  - matplotlib-base=3.10.6
  - matplotlib-inline=0.1.7
  - mccabe=0.7.0
  - mdurl=0.1.2
  - mistune=3.1.2
  - more-itertools=10.3.0
  - multidict=6.1.0
  - mypy_extensions=1.0.0
  - mysql=8.4.0
  - nbclient=0.10.2
  - nbconvert=7.16.6
  - nbconvert-core=7.16.6
  - nbconvert-pandoc=7.16.6
  - nbformat=5.10.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - notebook=7.0.8
  - notebook-shim=0.2.4
  - numexpr=2.11.0
  - numpy=2.0.1
  - numpy-base=2.0.1
  - numpydoc=1.9.0
  - openjpeg=2.5.2
  - openldap=2.6.10
  - openssl=3.0.18
  - overrides=7.4.0
  - packaging=25.0
  - pandas=2.3.3
  - pandoc=3.8
  - pandocfilters=1.5.1
  - parso=0.8.4
  - pathspec=0.12.1
  - pcre2=10.42
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.3.0
  - pip=25.2
  - pixman=0.46.4
  - platformdirs=4.3.7
  - pluggy=1.5.0
  - ply=3.11
  - prometheus_client=0.21.1
  - prompt-toolkit=3.0.52
  - prompt_toolkit=3.0.52
  - propcache=0.3.1
  - psutil=7.0.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pycares=4.10.0
  - pycodestyle=2.12.1
  - pycparser=2.23
  - pydocstyle=6.3.0
  - pyflakes=3.2.0
  - pygithub=2.4.0
  - pygments=2.19.1
  - pyjwt=2.10.1
  - pylint=3.3.8
  - pylint-venv=3.0.3
  - pyls-spyder=0.4.0
  - pynacl=1.6.0
  - pyobjc-core=10.1
  - pyobjc-framework-cocoa=10.1
  - pyobjc-framework-coreservices=10.1
  - pyobjc-framework-fsevents=10.1
  - pyparsing=3.2.0
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - pyqtwebengine=5.15.10
  - pysocks=1.7.1
  - python=3.10.18
  - python-dateutil=2.9.0post0
  - python-fastjsonschema=2.20.0
  - python-json-logger=3.2.1
  - python-lsp-black=2.0.0
  - python-lsp-jsonrpc=1.1.2
  - python-lsp-server=1.12.2
  - python-slugify=8.0.4
  - python-tzdata=2025.2
  - python.app=3
  - pytoolconfig=1.2.6
  - pytz=2025.2
  - pyuca=1.2
  - pyyaml=6.0.2
  - pyzmq=27.1.0
  - qdarkstyle=3.2.3
  - qstylizer=0.2.2
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtawesome=1.4.0
  - qtconsole=5.6.1
  - qtpy=2.4.3
  - readline=8.3
  - referencing=0.30.2
  - requests=2.32.5
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rich=14.2.0
  - rope=1.13.0
  - rpds-py=0.22.3
  - rtree=1.4.1
  - scikit-learn=1.7.2
  - scipy=1.15.3
  - send2trash=1.8.2
  - setuptools=80.9.0
  - sip=6.7.12
  - six=1.17.0
  - sniffio=1.3.0
  - snowballstemmer=3.0.1
  - sortedcontainers=2.4.0
  - soupsieve=2.5
  - sphinx=7.3.7
  - sphinxcontrib-applehelp=2.0.0
  - sphinxcontrib-devhelp=2.0.0
  - sphinxcontrib-htmlhelp=2.1.0
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=2.0.0
  - sphinxcontrib-serializinghtml=2.0.0
  - spyder=6.0.7
  - spyder-kernels=3.0.5
  - sqlite=3.50.2
  - stack_data=0.6.3
  - superqt=0.7.6
  - terminado=0.18.1
  - text-unidecode=1.3
  - textdistance=4.6.3
  - threadpoolctl=3.5.0
  - three-merge=0.1.1
  - tinycss2=1.4.0
  - tk=8.6.15
  - tomli=2.2.1
  - tomlkit=0.13.2
  - tornado=6.5.1
  - traitlets=5.14.3
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - tzdata=2025b
  - ujson=5.10.0
  - urllib3=2.5.0
  - uvloop=0.21.0
  - watchdog=6.0.0
  - wcwidth=0.2.13
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - whatthepatch=1.0.7
  - wheel=0.45.1
  - widgetsnbextension=4.0.13
  - wrapt=1.17.0
  - wurlitzer=3.1.1
  - xz=5.6.4
  - yaml=0.2.5
  - yapf=0.40.2
  - yarl=1.18.0
  - zeromq=4.3.5
  - zipp=3.21.0
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - filelock==3.20.0
      - fsspec==2025.9.0
      - h5py==3.15.0
      - mpmath==1.3.0
      - networkx==3.4.2
      - sympy==1.14.0
      - torch==2.8.0
      - torchaudio==2.8.0
      - torchvision==0.23.0
